### ISSUE TITLE
Hitable by * necessary in damage.nas?

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/OpRedFlag#17]
I do not understand the necessity of the hitable_* properties in damage.nas. Given that the plane decides whether or not something is visible in the radar and/or something has been hit (AramamentNotification with kind=4), why let the hit target at a later stage decide that it has been hit or not? And why not test for rockets vs. cannon and bombs vs. a/a missiles vs. a/g missiles?

var hitable_by_air_munitions = 1;   # if anti-air can do damage
var hitable_by_cannon = 1;          # if cannon can do damage
#var hitable_by_ground_munitions = 1;# if anti-ground/marine can do damage

If something should be made invulnerable, then that something can turn-off its damage registration, can bump hp_max to a very large number etc.

**Comment by NikolaiVChr** [comment]
Several reasons. One is make sure that people don't just modify their missile to be able to damage something it should not.
Second is that is just an extra check, to make 100% sure it doesn't happen.
